1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

In [2]:
#Numpy stored the data in a numpy array
#An array is a container/data structure used to store data of some data type>> homogenous
#numpy is built using C >> Numpy computation is fast
#due to array >> since it stores only homogenous data, numpy array is faster
#since it stores homogeous data>> contiguous/continuous memory location
#mathematical computation is fast
#Advantage of Numpy :NumPy is ideal for handling large amounts of homogeneous (same-type) data,
#offering significant improvements in speed and memory efficiency. It also provides high-level syntax for a wide range of numerical operations,
#making it a powerful tool for scientific computing and data processing on the CPU.

 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other?

In [1]:
#In NumPy, both np.mean() and np.average() are used to calculate the average of an array, but they differ in their functionality.

#np.mean()
#Purpose: Computes the arithmetic mean (average) along the specified axis.
#np.mean()
#It simply calculates the mean by summing up all the values and dividing by the number of elements. 
#There is no provision for weighted means.

#np.average()
#Purpose: Computes the weighted average along the specified axis.
# Use np.average() when you need to compute a weighted average, 
#or when you want the mean with an option to return the sum of weights.



#When to Use
#Use np.mean() when you need a simple average without considering any weights.
#Use np.average() when you need to calculate a weighted average or want to handle both the mean and the sum of weights in one function.

 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
arrays.

In [2]:
#Reversing a NumPy array along different axes can be done using various methods

#1D Array
#Slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


In [3]:
#np.flip()
reversed_arr = np.flip(arr)
print(reversed_arr)

[5 4 3 2 1]


In [4]:
#2D Array
#slicing
#Reverse along rows (axis 0):
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [5]:
#Reverse along columns (axis 1):
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [6]:
#Reverse both axes:
reversed_both = arr_2d[::-1, ::-1]
print(reversed_both)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [7]:
#np.flip()
#Reverse along rows (axis 0):
reversed_rows = np.flip(arr_2d, axis=0)
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [8]:
#Reverse along columns (axis 1):
reversed_columns = np.flip(arr_2d, axis=1)
print(reversed_columns)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [9]:
#Reverse both axes:
reversed_both = np.flip(arr_2d)
print(reversed_both)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
in memory management and performance

In [10]:
#Use array.dtype to determine the data type of elements in a NumPy array.

#importance
#Memory Management: Smaller data types use less memory, leading to more efficient memory usage.
#Performance: Choosing the right data type can improve computation speed and efficiency in operations.

 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [11]:
#An ndarray (N-dimensional array) is the core data structure in NumPy, representing a multi-dimensional, homogeneous array of fixed-size items.

#features>>
#N-Dimensional:ndarrays can have any number of dimensions.
#All elements in an ndarray have the same data type (dtype).
#Once an ndarray is created, its size (the total number of elements) cannot be changed.
#crucial for performance, especially in large-scale numerical computations.
#support broadcasting
#allow for advanced slicing and indexing techniques


#ndarrays in NumPy are powerful, multi-dimensional, homogeneous arrays designed for efficient numerical computation. 
#They differ significantly from Python lists in terms of memory efficiency, performance, and the types of operations they support,
#making them a cornerstone of scientific computing in Python.

 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [12]:
#Homogeneous Data Type: NumPy arrays are homogeneous, meaning all elements are of the same data type (dtype). 
#This allows NumPy to allocate memory more efficiently, using a fixed amount of space for each element. 
#Python lists, on the other hand, are heterogeneous and store references to objects, leading to additional overhead.

#The NumPy operation is significantly faster because it leverages low-level, highly optimized C code for the element-wise operations, 
#whereas the list operation requires Python to interpret and execute each loop iteration.

# Broadcasting allows NumPy to perform operations on arrays of different shapes without explicit replication of data
#In Python lists, a similar operation would require explicit looping or the use of list comprehensions, both of which are slower and less efficient.

# NumPy allows for advanced slicing and indexing techniques
#Python lists require copying data when slicing, which is slower and less memory efficient.


 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
output

In [13]:
#vstack(): 
#Concatenates arrays along the vertical axis (axis 0, row-wise).
#Arrays must have the same number of columns.


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


In [14]:
#hstack(): 
#Concatenates arrays along the horizontal axis (axis 1, column-wise).
#Arrays must have the same number of rows.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.hstack((arr1, arr2))
print(result)

[1 2 3 4 5 6]


 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
array dimensions

In [15]:
#fliplr(): Reverses the order of elements along the horizontal axis (columns).
#flipud(): Reverses the order of elements along the vertical axis (rows).

#Effect on 2D Arrays:
#fliplr(): Flips the array left to right, changing the order of columns.
#flipud(): Flips the array up to down, changing the order of rows.

#Effect on Higher-Dimensional Arrays:
#fliplr(): Operates on the last axis, flipping columns within each 2D slice.
#flipud(): Operates on the first axis, flipping rows within each 2D slice.

 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [16]:
#array_split() function in NumPy>> used to split an array into multiple sub-arrays.
#useful when dealing with tasks where you need to partition data into chunks of roughly equal size.

#Uneven Splits: 
#When the array size is not evenly divisible by the number of sections, 
#array_split() will create sub-arrays where some sub-arrays may have more elements than others.

arr = np.arange(10)
result = np.array_split(arr, 3)
print(result)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
operations?

In [17]:
#Vectorization >>
#refers to the process of applying operations to entire arrays (or large blocks of data) at once, 
#rather than iterating through individual elements with explicit loops.
#Efficiency: Vectorization leverages low-level optimizations and parallelism provided by the underlying libraries (such as BLAS, LAPACK) and the CPU.

#Broadcasting >>
#refers to the ability of NumPy to perform element-wise operations on arrays of different shapes, 
#by automatically "expanding" the smaller array(s) to match the shape of the larger one(s).
#Efficiency: saves memory and reduces computational overhead

PRACTICAL QUESTIONS:

 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,101,size=(3,3))

In [4]:
print(arr)

[[16 54 92]
 [36 13 71]
 [13 46  7]]


In [6]:
arr.T  #interchange its rows and columns

array([[16, 36, 13],
       [54, 13, 46],
       [92, 71,  7]])

 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [7]:
ar = np.arange(10)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
ar_2x5 = ar.reshape(2,5)
print(ar_2x5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
ar_5x2 = ar_2x5.reshape(5,2)
print(ar_5x2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [14]:
arr1 = np.random.random((4,4))
print(arr1)

[[0.67751312 0.28933855 0.43298684 0.48354142]
 [0.64369692 0.44381683 0.66665097 0.01646736]
 [0.47488846 0.23251292 0.2944768  0.36719243]
 [0.15497259 0.56050305 0.29542551 0.42555511]]


In [15]:
arr2 = np.pad(arr1, pad_width=1, mode='constant', constant_values=0)
print(arr2) 

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.67751312 0.28933855 0.43298684 0.48354142 0.        ]
 [0.         0.64369692 0.44381683 0.66665097 0.01646736 0.        ]
 [0.         0.47488846 0.23251292 0.2944768  0.36719243 0.        ]
 [0.         0.15497259 0.56050305 0.29542551 0.42555511 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [16]:
array = np.arange(10,61,5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element.

In [17]:
array = np.array(['pandas','numpy','pandas'])
print(array)

['pandas' 'numpy' 'pandas']


In [18]:
up_arr = np.char.upper(array)
print(up_arr)

['PANDAS' 'NUMPY' 'PANDAS']


In [19]:
lw_ar = np.char.lower(array)
print(lw_ar)

['pandas' 'numpy' 'pandas']


In [21]:
tl_ar = np.char.title(array)
print(tl_ar)

['Pandas' 'Numpy' 'Pandas']


In [22]:
cp_ar = np.char.capitalize(array)
print(cp_ar)

['Pandas' 'Numpy' 'Pandas']


In [23]:
sp_ar = np.char.swapcase(array)
print(sp_ar)

['PANDAS' 'NUMPY' 'PANDAS']


 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [28]:
wd = np.array(['Aadarsh','Hitesh','Gaurav','Karan','Ritesh'])

def insert_spaces(word):
    return ' '.join(word)

spacearray = np.vectorize(insert_spaces)(wd)
print(spacearray)

['A a d a r s h' 'H i t e s h' 'G a u r a v' 'K a r a n' 'R i t e s h']


 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = np.array([[7, 8, 9], [10, 11, 12]])
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [33]:
#addition
print(a+b)

[[ 8 10 12]
 [14 16 18]]


In [34]:
#substraction
print(a-b)

[[-6 -6 -6]
 [-6 -6 -6]]


In [35]:
#multiplication
print(a*b)

[[ 7 16 27]
 [40 55 72]]


In [36]:
#division
print(a/b)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [38]:
id_mx = np.eye(5)
print(id_mx)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
dg_element = np.diag(id_mx)
print(dg_element)

[1. 1. 1. 1. 1.]


 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.

In [41]:
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

In [42]:
arr = np.random.randint(1,1001,size=100)
print(arr)

[635 978 852 368 554 360 826 914 630  30 108 233 714 760 353  14 528 997
 721 918 579 464 858 660 881 795 926 458 823 142 506  82 524 643 936 784
 682 900 131 204 225 486 573 529 286 562 332 281 661 231 605 268   1 108
 525 483 627 267 748 509 384 689  30 564 158 494 254 499 513 703 771 888
  80 936 128 677 898 498 541 312  15 581   3 127 911 905 942 460 246 449
 718 966 594 951 619 392 882 390 625 903]


In [43]:
prime_numbers = np.array([num for num in arr if is_prime(num)])
print(prime_numbers)

[233 353 997 881 823 643 131 281 661 509 499 677 541   3 127 911 449 619]


 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages

In [62]:
daily_temperatures = np.random.randint(0, 40, size=30)

weekly_temperatures = daily_temperatures.reshape(4, 7)

weekly_averages = np.mean(weekly_temperatures, axis=1)
print(weekly_averages)

ValueError: cannot reshape array of size 30 into shape (4,7)